### ISSUE TITLE
No issue here

### ISSUE THREAD

**Issue by world** [DevAndArtist/SingletonGenerator#1]
Just wanted to say this is really cool. I am sure this is Swift 2.2 compatible yes? The only downfalls I see, and I am sure there are limits of Swift are:
1. Not being able to force the classes that use them to be predicated with "final" to prevent subclassing.
2. Not being able to force the init to be "private" to prevent re-initing and violating the singleton concept 

Thoughts? 

Again thank you!

**Comment by DevAndArtist** [comment]
@world I can't remember, but I think it should be compatible with Swift 2.2. I had not time yet to update it to Swift 3.

I'm not sure if we ever see any features in Swift which will allow us to hide initializers like this.
